### ISSUE TITLE
About Experiment Environment

### ISSUE THREAD

**Issue by matsutakk** [aaron-vuw/gmeql#1]
Hi, from japan.

I've read your paper and it was really interesting because GP can be replace with gradient-based method.

I would like to your experiments on my own computer, so, if you have time, Could you tell me your tensorflow version??

Thank you.

**Comment by aaron-vuw** [comment]
The tensorflow version I used is 1.14.0.

Before running the algorithm, please check and set preserveBaseProb to 0.8 (or a similar value) in the code.

Thanks!

**Comment by matsutakk** [comment]
Thank you!!
